"""Production schema

Revision ID: 5dfa55165ac4
Revises: 
Create Date: 2026-02-09 19:26:01.790325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dfa55165ac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_compound_source_external_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checksums', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('proteins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_protein_source_external_id')
    )
    op.create_index('ix_compounds_source_external', 'compounds', ['source', 'external_id'], unique=False)
    op.create_index('ix_proteins_source_external', 'proteins', ['source', 'external_id'], unique=False)
    op.create_index('ix_ingestion_runs_source', 'ingestion_runs', ['source'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('protein_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('affinity_value', sa.Float(), nullable=True),
    sa.Column('affinity_unit', sa.String(), nullable=True),
    sa.Column('assay_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_interaction_source_external_id')
    )
    op.create_index(op.f('ix_interactions_compound_id'), 'interactions', ['compound_id'], unique=False)
    op.create_index(op.f('ix_interactions_protein_id'), 'interactions', ['protein_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_protein_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_compound_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('proteins')
    op.drop_table('ingestion_runs')
    op.drop_table('compounds')
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
